//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBetsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int Id { get; set; }
        public string AuctionName { get; set; }
        public decimal InitialBet { get; set; }
        public int UsedItem { get; set; }
        public string Auctioneer { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
    }
}
