//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBetsAPI.Models
{
  using System.Data.Entity;

  public partial class MyBetsDBEntities : DbContext
  {
    public MyBetsDBEntities()
        : base("name=MyBetsDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);
      modelBuilder.Entity<Auction>().ToTable("Auctions");
      modelBuilder.Entity<User>().ToTable("Users");
    }

    public virtual DbSet<Auction> Auctions { get; set; }
    public virtual DbSet<User> Users { get; set; }
  }
}
